//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingKhoiLuan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public int employee_id { get; set; }
        [Required(ErrorMessage ="Hãy nhập vào họ và tên")]
        public string employee_name { get; set; }
        [Required(ErrorMessage = "Hãy chọn ngày tháng năm sinh")]
        public Nullable<System.DateTime> birth_date { get; set; }
        [Required(ErrorMessage ="Hãy nhập vào ngày sinh")]
        public string birth_place { get; set; }
        [Required]
        [Range(1,100, ErrorMessage ="Phải nhập kí tự số")]
        public Nullable<int> age { get; set; }
    }
}
